export const STORED_ACCOUNTS = "BUNQDESKTOP_STORED_ACCOUNTS";
export const SELECTED_ACCOUNT_LOCATION = "BUNQDESKTOP_SELECTED_ACCOUNT";
export const EXCLUDED_ACCOUNT_IDS = "BUNQDESKTOP_EXCLUDED_ACCOUNT_IDS";

export const STORED_BUNQ_ME_TABS = "BUNQDESKTOP_STORED_BUNQ_ME_TABS";

export const CARD_ORDER_LOCATION = "BUNQDESKTOP_CARD_ORDER";

export const BUNQDESKTOP_CATEGORIES = "BUNQDESKTOP_CATEGORIES";
export const BUNQDESKTOP_CATEGORY_CONNECTIONS = "BUNQDESKTOP_CATEGORY_CONNECTIONS";

export const STORED_CATEGORY_RULES = "BUNQDESKTOP_STORED_CATEGORY_RULES";

export const STORED_CONTACTS = "BUNQDESKTOP_STORED_CONTACTS";
